import type {Metadata} from "next";
import "./globals.css";
import {ThemeProvider} from "@/app/ThemeContext";
import {VideoProvider} from "@/app/VideoProvider";
import Aside from "@/app/components/aside/aside";
import StyleSwitcher from "@/app/components/style-switcher";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <ThemeProvider>
            <VideoProvider>
                <html lang="en">
                <body>
                <Aside/>
                {children}
                <StyleSwitcher/>
                </body>
                </html>
            </VideoProvider>
        </ThemeProvider>
    );
}
