import type {Metadata} from "next";
import "./globals.css";
import {ThemeProvider} from "@/app/ThemeContext";
import {VideoProvider} from "@/app/VideoProvider";
import Page from "@/app/page";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <ThemeProvider>
            <VideoProvider>
                <html lang="ru">
                <body>
                    <Page />
                    {children}
                </body>
                </html>
            </VideoProvider>
        </ThemeProvider>
    );
}
